# Generated by Django 5.2.14 on 2026-05-16 15:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("REAL_ESTATE", "Immobilier"),
                            ("LAND", "Foncier"),
                            ("BANK_ACCOUNT", "Compte bancaire"),
                            ("CASH", "Liquidités"),
                            ("GOLD", "Or"),
                            ("BUSINESS", "Commerce"),
                            ("SHARES", "Parts sociales"),
                            ("AGRICULTURE", "Agriculture"),
                            ("LIVESTOCK", "Élevage"),
                            ("WAQF_ASSET", "Actif waqf"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="cases.fiduciarycase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("asset_type", "label"),
            },
        ),
        migrations.CreateModel(
            name="AssetIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Loyer"),
                            ("DIVIDEND", "Dividende"),
                            ("INTEREST", "Intérêts"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ("-period_end", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AssetRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MARKET", "Marché"),
                            ("LEGAL", "Juridique"),
                            ("OPERATIONAL", "Opérationnel"),
                            ("CHARIA", "Charaïque"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                ("identified_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_risks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-identified_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AssetValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("valued_at", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MARKET", "Marché"),
                            ("EXPERT", "Expertise"),
                            ("BOOK", "Valeur comptable"),
                            ("OTHER", "Autre"),
                        ],
                        default="MARKET",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_valuations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-valued_at", "-created_at"),
            },
        ),
    ]
