# Generated by Django 5.2.14 on 2026-05-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0001_initial"),
        ("cases", "0002_case_type_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="relation_to_donor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHILD", "Enfant"),
                    ("SPOUSE", "Conjoint(e)"),
                    ("PARENT", "Parent"),
                    ("SIBLING", "Frère / sœur"),
                    ("HEIR", "Héritier / héritière"),
                    ("WARD", "Protégé(e) / pupille"),
                    ("OTHER", "Autre"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CaseDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=128)),
                ("identification_number", models.CharField(blank=True, max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donors",
                        to="cases.fiduciarycase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donateur",
                "verbose_name_plural": "Donateurs",
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiaries",
                to="beneficiaries.casedonor",
            ),
        ),
    ]
