# Generated by Django 5.2.14 on 2026-05-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0002_donor_and_beneficiary_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorTrustedPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("relationship_label", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_persons",
                        to="beneficiaries.casedonor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personne de confiance",
                "verbose_name_plural": "Personnes de confiance",
                "ordering": ("last_name", "first_name"),
            },
        ),
    ]
