# Generated by Django 5.2.14 on 2026-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0003_donor_trusted_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donortrustedperson",
            name="relationship_label",
            field=models.CharField(
                blank=True,
                help_text="Lien avec le donateur (ex. frère, notaire de famille).",
                max_length=128,
            ),
        ),
    ]
