# Generated by Django 5.2.14 on 2026-05-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_case_type_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaqfProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waqf_type",
                    models.CharField(
                        choices=[
                            ("FAMILY", "Waqf familial"),
                            ("PRODUCTIVE", "Waqf productif"),
                            ("MIXED", "Mixte"),
                        ],
                        default="FAMILY",
                        max_length=32,
                    ),
                ),
                ("waqf_object", models.TextField(blank=True)),
                ("waqf_distribution_rules", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waqf_profile",
                        to="cases.fiduciarycase",
                    ),
                ),
            ],
        ),
    ]
