# Generated by Django 5.2.14 on 2026-06-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("CASE_SUBMITTED", "Dossier soumis"),
                    ("REPORT_APPROVED", "Rapport approuvé"),
                    ("VALIDATION_PENDING", "Validation en attente"),
                    ("ASSET_VALUATION_DUE", "Réévaluation patrimoine"),
                    ("FARAID_REVIEW_REQUESTED", "Partage farāʾiḍ à traiter"),
                    ("GENERAL", "Information"),
                ],
                default="GENERAL",
                max_length=32,
            ),
        ),
    ]
