# Generated by Django 5.2.14 on 2026-07-13 08:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0005_case_observations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmanahManagementProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("code_ar", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "target_yield_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "target_yield_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Profil de gestion AMANAH",
                "verbose_name_plural": "Profils de gestion AMANAH",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentAssetClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "weight_min",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Poids cible minimum (%) dans l'univers PIGFI.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "weight_max",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Poids cible maximum (%) dans l'univers PIGFI.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Classe d'actif PIGFI",
                "verbose_name_plural": "Classes d'actifs PIGFI",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="PatrimonyInvestmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("A", "Catégorie A — Mineurs"),
                            ("B", "Catégorie B — Successoraux"),
                            ("C", "Catégorie C — Familial long terme"),
                            ("D", "Catégorie D — Waqf"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("objective", models.TextField(blank=True)),
                (
                    "target_yield_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "target_yield_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "allocation_targets",
                    models.JSONField(
                        default=dict,
                        help_text="Répartition cible par slug de classe d'actif (%, total ~100).",
                    ),
                ),
                (
                    "default_case_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Types de dossier associés par défaut (codes CaseType).",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Catégorie patrimoniale PIGFI",
                "verbose_name_plural": "Catégories patrimoniales PIGFI",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=120)),
                (
                    "amount_invested",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                ("start_date", models.DateField()),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VALIDATION", "En attente de validation"),
                            ("ACTIVE", "Actif"),
                            ("MATURED", "Arrivé à échéance"),
                            ("CLOSED", "Clôturé"),
                        ],
                        default="PENDING_VALIDATION",
                        max_length=32,
                    ),
                ),
                (
                    "annual_yield_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "distributed_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "sharia_compliance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("requires_purification", models.BooleanField(default=False)),
                (
                    "purification_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="cases.fiduciarycase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="investments.investmentassetclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investissement",
                "verbose_name_plural": "Investissements",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseInvestmentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sharia_compliance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_policy",
                        to="cases.fiduciarycase",
                    ),
                ),
                (
                    "management_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_policies",
                        to="investments.amanahmanagementprofile",
                    ),
                ),
                (
                    "patrimony_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_policies",
                        to="investments.patrimonyinvestmentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Politique d'investissement dossier",
                "verbose_name_plural": "Politiques d'investissement dossier",
            },
        ),
        migrations.AddField(
            model_name="amanahmanagementprofile",
            name="linked_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="management_profiles",
                to="investments.patrimonyinvestmentcategory",
            ),
        ),
    ]
