# Generated by Django 5.2.14 on 2026-07-13 09:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0007_beneficiary_parents_gender"),
        ("investments", "0002_seed_pigfi_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "share_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Part de l'investissement total (0–100 %).",
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_participations",
                        to="beneficiaries.beneficiary",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="investments.investment",
                    ),
                ),
                (
                    "patrimony_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_participations",
                        to="investments.patrimonyinvestmentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant investissement",
                "verbose_name_plural": "Participants investissement",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("investment", "beneficiary", "patrimony_category"),
                        name="unique_investment_beneficiary_category",
                    )
                ],
            },
        ),
    ]
