# Generated by Django 5.2.14 on 2026-05-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiduciaryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("UNDER_REVIEW", "En revue"),
                            ("LEGAL_REVIEW", "Revue juridique"),
                            ("COMPLIANCE_REVIEW", "Revue conformité"),
                            ("ACTIVE", "Actif"),
                            ("SUSPENDED", "Suspendu"),
                            ("CLOSING", "En clôture"),
                            ("CLOSED", "Clôturé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier fiduciaire",
                "verbose_name_plural": "Dossiers fiduciaires",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CaseTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Création"),
                            ("UPDATED", "Mise à jour"),
                            ("STATUS_CHANGED", "Changement de statut"),
                            ("SUBMITTED", "Soumission"),
                            ("CLOSED", "Clôture"),
                            ("NOTE_ADDED", "Note ajoutée"),
                            ("STAKEHOLDER_ADDED", "Partie prenante ajoutée"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="cases.fiduciarycase",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="cases.fiduciarycase",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CaseStakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("FIDUCIARY_AGENT", "Agent fiduciaire"),
                            ("DIRECTION", "Direction"),
                            ("LEGAL", "Juridique"),
                            ("ACCOUNTING", "Comptabilité"),
                            ("CHARIA", "Comité charaïque"),
                            ("FAMILY", "Famille"),
                            ("GUARDIAN", "Tuteur"),
                            ("NOTARY", "Notaire"),
                            ("JUDGE", "Juge"),
                            ("AUDITOR", "Auditeur"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_stakeholders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="cases.fiduciarycase",
                    ),
                ),
            ],
            options={
                "ordering": ("case_id", "role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "user", "role"),
                        name="cases_stakeholder_case_user_role_uniq",
                    )
                ],
            },
        ),
    ]
