# Generated by Django 5.2.14 on 2026-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiduciarycase",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("TUTELLE_CANTONNEMENT", "Tutelle / cantonnement"),
                    ("MANDAT_FIDUCIAIRE", "Mandat fiduciaire"),
                    ("WAQF", "Waqf familial ou productif"),
                    ("SUCCESSION", "Conseil successoral"),
                    ("ZAKAT_FARAID", "Zakat & farāʾiḍ"),
                ],
                default="MANDAT_FIDUCIAIRE",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="fiduciarycase",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiduciarycase",
            name="onboarding_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fiduciarycase",
            name="onboarding_step",
            field=models.CharField(blank=True, default="identification", max_length=32),
        ),
    ]
