# Generated by Django 5.2.14 on 2026-06-29 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetimelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Création"),
                    ("UPDATED", "Mise à jour"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("SUBMITTED", "Soumission"),
                    ("CLOSED", "Clôture"),
                    ("NOTE_ADDED", "Note ajoutée"),
                    ("OBSERVATION_SHARED", "Observation partagée"),
                    ("OBSERVATION_APPROVED", "Observation retenue"),
                    ("OBSERVATION_REJECTED", "Observation refusée"),
                    ("REMARK_ADDED", "Remarque interne"),
                    ("STAKEHOLDER_ADDED", "Partie prenante ajoutée"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CaseObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SUBMISSION", "Observation partagée"),
                            ("REMARK", "Remarque interne"),
                        ],
                        default="SUBMISSION",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente de validation"),
                            ("APPROVED", "Retenue"),
                            ("REJECTED", "Refusée"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="cases.fiduciarycase",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_observations_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
