# Generated by Django 5.2.14 on 2026-05-17 16:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0004_alter_donortrustedperson_relationship_label"),
        ("cases", "0002_case_type_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaraidHeir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("relationship_label", models.CharField(blank=True, max_length=128)),
                (
                    "share_fraction",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Fraction théorique (ex. 0.25 pour 25 %).",
                        max_digits=8,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faraid_entries",
                        to="beneficiaries.beneficiary",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faraid_heirs",
                        to="cases.fiduciarycase",
                    ),
                ),
            ],
            options={
                "ordering": ("-share_fraction", "full_name"),
            },
        ),
    ]
