# Generated by Django 5.2.14 on 2026-05-14 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="ExternalPartyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("FAMILLE", "Famille"),
                            ("TUTEUR", "Tuteur"),
                            ("NOTAIRE", "Notaire"),
                            ("JURIDICTION", "Juridiction"),
                            ("PARTENAIRE", "Partenaire"),
                            ("INSTITUTION", "Institution"),
                        ],
                        max_length=32,
                    ),
                ),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_party_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                (
                    "locale",
                    models.CharField(blank=True, default="fr-FR", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super administration"),
                            ("DIRECTION", "Direction"),
                            ("AGENT_FIDUCIAIRE", "Agent fiduciaire"),
                            ("JURIDIQUE_CONFORMITE", "Juridique / conformité"),
                            ("COMPTABLE_FIDUCIAIRE", "Comptable fiduciaire"),
                            ("COMITE_CHARAIQUE", "Comité charaique"),
                            ("AUDITEUR", "Auditeur"),
                            ("FAMILLE_TUTEUR", "Famille / tuteur"),
                            ("NOTAIRE", "Notaire"),
                            ("JUGE", "Juge"),
                        ],
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments",
                        to="accounts.accessscope",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user_id", "role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"),
                        name="accounts_roleassignment_user_role_uniq",
                    )
                ],
            },
        ),
    ]
