# Generated by Django 5.2.14 on 2026-05-16 16:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=128)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Recette"),
                            ("EXPENSE", "Dépense"),
                            ("TRANSFER", "Virement"),
                            ("MANAGEMENT_FEE", "Frais de gestion"),
                            ("PERFORMANCE_FEE", "Frais de performance"),
                            ("ADJUSTMENT", "Ajustement"),
                        ],
                        default="EXPENSE",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "movement categories",
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="FiduciaryAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiduciary_accounts",
                        to="cases.fiduciarycase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiduciary_accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Recette"),
                            ("EXPENSE", "Dépense"),
                            ("TRANSFER", "Virement"),
                            ("MANAGEMENT_FEE", "Frais de gestion"),
                            ("PERFORMANCE_FEE", "Frais de performance"),
                            ("ADJUSTMENT", "Ajustement"),
                        ],
                        default="MANAGEMENT_FEE",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="finance.fiduciaryaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-due_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="FinancialMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Recette"),
                            ("EXPENSE", "Dépense"),
                            ("TRANSFER", "Virement"),
                            ("MANAGEMENT_FEE", "Frais de gestion"),
                            ("PERFORMANCE_FEE", "Frais de performance"),
                            ("ADJUSTMENT", "Ajustement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("description", models.CharField(blank=True, max_length=512)),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("movement_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING_VALIDATION", "En validation"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="finance.fiduciaryaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_movements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_movements",
                        to="documents.document",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="finance.movementcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-movement_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("bank_balance", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "ledger_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="finance.fiduciaryaccount",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-period_end",),
            },
        ),
    ]
