# Generated by Django 5.2.14 on 2026-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_category_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementcategory",
            name="scope",
            field=models.CharField(
                choices=[
                    ("REVENUE", "Recette / chiffre d'affaires"),
                    ("EXPENSE", "Dépense"),
                    ("NEUTRAL", "Neutre"),
                ],
                default="EXPENSE",
                max_length=16,
            ),
        ),
    ]
