# Generated by Django 5.2.14 on 2026-05-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0004_alter_donortrustedperson_relationship_label"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="beneficiaries.casedonor",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="identity_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CNI", "Carte nationale d'identité"),
                    ("CNI_VERSO", "CNI (verso)"),
                    ("EN", "Extrait de naissance"),
                    ("PASSPORT", "Passeport"),
                    ("RESIDENCE", "Certificat de résidence"),
                    ("OTHER", "Autre pièce d'identité"),
                ],
                help_text="Type de pièce d'identité du donateur (nommage automatique).",
                max_length=32,
            ),
        ),
    ]
