# Generated by Django 5.2.14 on 2026-07-20 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("TUTELLE_CANTONNEMENT", "Tutelle / cantonnement"),
                            ("MANDAT_FIDUCIAIRE", "Mandat fiduciaire"),
                            ("WAQF", "Waqf familial ou productif"),
                            ("SUCCESSION", "Conseil successoral"),
                            ("ZAKAT_FARAID", "Zakat & farāʾiḍ"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ServiceBillingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        choices=[
                            ("MANAGEMENT_FEE_AUM", "Frais de gestion (AUM)"),
                            ("PERFORMANCE_FEE", "Commission de performance"),
                            ("OPENING_FEE", "Honoraires d'ouverture / mandat"),
                            ("MISSION_FEE", "Honoraires de mission"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rate_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Taux par défaut (%) pour les formules proportionnelles.",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "rate_min_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "rate_max_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant forfaitaire (XOF) pour honoraires ponctuels.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=3)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("ONCE", "Ponctuel (à l'ouverture / mission)"),
                            ("QUARTERLY", "Trimestriel"),
                            ("ANNUAL", "Annuel"),
                            ("ON_PROFIT", "Sur profit positif"),
                        ],
                        default="ONCE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_billing_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rules",
                        to="services.serviceoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle tarifaire",
                "verbose_name_plural": "Règles tarifaires",
                "ordering": ("service_id", "sort_order", "id"),
            },
        ),
    ]
