# Generated by Django 5.2.14 on 2026-07-27 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_case_observations"),
        ("finance", "0007_case_billing_charge"),
        ("services", "0006_servicebillingrule_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_label", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("movement_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("POSTED", "Comptabilisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_invoices",
                        to="cases.fiduciarycase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enterprise_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_invoice",
                        to="finance.enterprisemovement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture d'honoraires",
                "verbose_name_plural": "Factures d'honoraires",
                "ordering": ("-movement_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="BillingInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        choices=[
                            ("MANAGEMENT_FEE_AUM", "Frais de gestion (AUM)"),
                            ("PERFORMANCE_FEE", "Commission de performance"),
                            ("OPENING_FEE", "Honoraires d'ouverture / mandat"),
                            ("MISSION_FEE", "Honoraires de mission"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "base_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("is_selected", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "billing_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_lines",
                        to="services.servicebillingrule",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="services.billinginvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture",
                "verbose_name_plural": "Lignes de facture",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
