/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceZakatFaraidRouteImport } from './routes/service-zakat-faraid'
import { Route as ServiceWaqfFamilialRouteImport } from './routes/service-waqf-familial'
import { Route as ServiceReportingRouteImport } from './routes/service-reporting'
import { Route as ServiceProtectionFamilialeRouteImport } from './routes/service-protection-familiale'
import { Route as ServiceMandatFiduciaireRouteImport } from './routes/service-mandat-fiduciaire'
import { Route as ServiceConseilSuccessoralIslamiqueRouteImport } from './routes/service-conseil-successoral-islamique'
import { Route as ServiceConformiteCharaiqueRouteImport } from './routes/service-conformite-charaique'
import { Route as ServiceCantonnementActifsRouteImport } from './routes/service-cantonnement-actifs'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceZakatFaraidRoute = ServiceZakatFaraidRouteImport.update({
  id: '/service-zakat-faraid',
  path: '/service-zakat-faraid',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceWaqfFamilialRoute = ServiceWaqfFamilialRouteImport.update({
  id: '/service-waqf-familial',
  path: '/service-waqf-familial',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceReportingRoute = ServiceReportingRouteImport.update({
  id: '/service-reporting',
  path: '/service-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceProtectionFamilialeRoute =
  ServiceProtectionFamilialeRouteImport.update({
    id: '/service-protection-familiale',
    path: '/service-protection-familiale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceMandatFiduciaireRoute = ServiceMandatFiduciaireRouteImport.update({
  id: '/service-mandat-fiduciaire',
  path: '/service-mandat-fiduciaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceConseilSuccessoralIslamiqueRoute =
  ServiceConseilSuccessoralIslamiqueRouteImport.update({
    id: '/service-conseil-successoral-islamique',
    path: '/service-conseil-successoral-islamique',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceConformiteCharaiqueRoute =
  ServiceConformiteCharaiqueRouteImport.update({
    id: '/service-conformite-charaique',
    path: '/service-conformite-charaique',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceCantonnementActifsRoute =
  ServiceCantonnementActifsRouteImport.update({
    id: '/service-cantonnement-actifs',
    path: '/service-cantonnement-actifs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/service-cantonnement-actifs': typeof ServiceCantonnementActifsRoute
  '/service-conformite-charaique': typeof ServiceConformiteCharaiqueRoute
  '/service-conseil-successoral-islamique': typeof ServiceConseilSuccessoralIslamiqueRoute
  '/service-mandat-fiduciaire': typeof ServiceMandatFiduciaireRoute
  '/service-protection-familiale': typeof ServiceProtectionFamilialeRoute
  '/service-reporting': typeof ServiceReportingRoute
  '/service-waqf-familial': typeof ServiceWaqfFamilialRoute
  '/service-zakat-faraid': typeof ServiceZakatFaraidRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/service-cantonnement-actifs': typeof ServiceCantonnementActifsRoute
  '/service-conformite-charaique': typeof ServiceConformiteCharaiqueRoute
  '/service-conseil-successoral-islamique': typeof ServiceConseilSuccessoralIslamiqueRoute
  '/service-mandat-fiduciaire': typeof ServiceMandatFiduciaireRoute
  '/service-protection-familiale': typeof ServiceProtectionFamilialeRoute
  '/service-reporting': typeof ServiceReportingRoute
  '/service-waqf-familial': typeof ServiceWaqfFamilialRoute
  '/service-zakat-faraid': typeof ServiceZakatFaraidRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/service-cantonnement-actifs': typeof ServiceCantonnementActifsRoute
  '/service-conformite-charaique': typeof ServiceConformiteCharaiqueRoute
  '/service-conseil-successoral-islamique': typeof ServiceConseilSuccessoralIslamiqueRoute
  '/service-mandat-fiduciaire': typeof ServiceMandatFiduciaireRoute
  '/service-protection-familiale': typeof ServiceProtectionFamilialeRoute
  '/service-reporting': typeof ServiceReportingRoute
  '/service-waqf-familial': typeof ServiceWaqfFamilialRoute
  '/service-zakat-faraid': typeof ServiceZakatFaraidRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/impact'
    | '/service-cantonnement-actifs'
    | '/service-conformite-charaique'
    | '/service-conseil-successoral-islamique'
    | '/service-mandat-fiduciaire'
    | '/service-protection-familiale'
    | '/service-reporting'
    | '/service-waqf-familial'
    | '/service-zakat-faraid'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/impact'
    | '/service-cantonnement-actifs'
    | '/service-conformite-charaique'
    | '/service-conseil-successoral-islamique'
    | '/service-mandat-fiduciaire'
    | '/service-protection-familiale'
    | '/service-reporting'
    | '/service-waqf-familial'
    | '/service-zakat-faraid'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/impact'
    | '/service-cantonnement-actifs'
    | '/service-conformite-charaique'
    | '/service-conseil-successoral-islamique'
    | '/service-mandat-fiduciaire'
    | '/service-protection-familiale'
    | '/service-reporting'
    | '/service-waqf-familial'
    | '/service-zakat-faraid'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  ServiceCantonnementActifsRoute: typeof ServiceCantonnementActifsRoute
  ServiceConformiteCharaiqueRoute: typeof ServiceConformiteCharaiqueRoute
  ServiceConseilSuccessoralIslamiqueRoute: typeof ServiceConseilSuccessoralIslamiqueRoute
  ServiceMandatFiduciaireRoute: typeof ServiceMandatFiduciaireRoute
  ServiceProtectionFamilialeRoute: typeof ServiceProtectionFamilialeRoute
  ServiceReportingRoute: typeof ServiceReportingRoute
  ServiceWaqfFamilialRoute: typeof ServiceWaqfFamilialRoute
  ServiceZakatFaraidRoute: typeof ServiceZakatFaraidRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-zakat-faraid': {
      id: '/service-zakat-faraid'
      path: '/service-zakat-faraid'
      fullPath: '/service-zakat-faraid'
      preLoaderRoute: typeof ServiceZakatFaraidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-waqf-familial': {
      id: '/service-waqf-familial'
      path: '/service-waqf-familial'
      fullPath: '/service-waqf-familial'
      preLoaderRoute: typeof ServiceWaqfFamilialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-reporting': {
      id: '/service-reporting'
      path: '/service-reporting'
      fullPath: '/service-reporting'
      preLoaderRoute: typeof ServiceReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-protection-familiale': {
      id: '/service-protection-familiale'
      path: '/service-protection-familiale'
      fullPath: '/service-protection-familiale'
      preLoaderRoute: typeof ServiceProtectionFamilialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-mandat-fiduciaire': {
      id: '/service-mandat-fiduciaire'
      path: '/service-mandat-fiduciaire'
      fullPath: '/service-mandat-fiduciaire'
      preLoaderRoute: typeof ServiceMandatFiduciaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-conseil-successoral-islamique': {
      id: '/service-conseil-successoral-islamique'
      path: '/service-conseil-successoral-islamique'
      fullPath: '/service-conseil-successoral-islamique'
      preLoaderRoute: typeof ServiceConseilSuccessoralIslamiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-conformite-charaique': {
      id: '/service-conformite-charaique'
      path: '/service-conformite-charaique'
      fullPath: '/service-conformite-charaique'
      preLoaderRoute: typeof ServiceConformiteCharaiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-cantonnement-actifs': {
      id: '/service-cantonnement-actifs'
      path: '/service-cantonnement-actifs'
      fullPath: '/service-cantonnement-actifs'
      preLoaderRoute: typeof ServiceCantonnementActifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  ServiceCantonnementActifsRoute: ServiceCantonnementActifsRoute,
  ServiceConformiteCharaiqueRoute: ServiceConformiteCharaiqueRoute,
  ServiceConseilSuccessoralIslamiqueRoute:
    ServiceConseilSuccessoralIslamiqueRoute,
  ServiceMandatFiduciaireRoute: ServiceMandatFiduciaireRoute,
  ServiceProtectionFamilialeRoute: ServiceProtectionFamilialeRoute,
  ServiceReportingRoute: ServiceReportingRoute,
  ServiceWaqfFamilialRoute: ServiceWaqfFamilialRoute,
  ServiceZakatFaraidRoute: ServiceZakatFaraidRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
